### ISSUE TITLE
VS2022 疑似无法读取 zh-hans 文件夹

### ISSUE THREAD

**Issue by jianxuanbing** [stratosblue/IntelliSenseLocalizer#12]
VS2022 17.11.4 这个版本，好像无法读取到 `zh-hans`文件夹中的XML内容了

**Comment by stratosblue** [comment]
嗯？是找到原因了吗？我看了下，我这里 17.11.4 是正常的

**Comment by jianxuanbing** [comment]
> 嗯？是找到原因了吗？我看了下，我这里 17.11.4 是正常的

SDK版本问题，VS2022 默认用 6.0.33 版本，而如果仅安装 6.0.32 版本，那么就没法正常显示了
