### ISSUE TITLE
下载的临时文件保存在那个路径了

### ISSUE THREAD

**Issue by HOILUNG** [stratosblue/IntelliSenseLocalizer#2]
也不知道文件有多大,下载太慢了.
下载了好久没完成,,有时候提示访问 docs.microsoft.com这个域名异常,这个域名已经做301到新的地址了.可能造成部分文件访问异常,
临时文件下载到那个目录了.会自动清理删除吗?不可以清理的话,我想手动删除

**Comment by HOILUNG** [comment]
C:\Users\{用户名}\AppData\Local\Temp\IntelliSenseLocalizer

临时路径找到了.生成了一个 压缩包.有需要的同志直接用吧, 6.0 的zh-cn
[net6.0@zh-cn@OriginFirst.zip](https://github.com/stratosblue/IntelliSenseLocalizer/files/9918949/net6.0%40zh-cn%40OriginFirst.zip)

**Comment by stratosblue** [comment]
@HOILUNG 
哈哈哈，首先感谢支持，用户引导这块做得确实不好（没有）。

- 自行构建的话确实很慢，也不好做更细的进度，大小也是无法预估的。
- 你说的访问 docs.microsoft.com 域名问题我抽空看看什么情况，构建过程中如果有一点异常也是正常的。
- 临时文件存放位置可以通过 `islocalizer build -h` 命令在输出中看到。
- 临时文件不会自动清除，主要是便于用于重复构建，提供了 `islocalizer clear` 来清理临时文件。
- 中文的话.net6和.net7我都已经生成了完整包，放在了 https://github.com/stratosblue/IntelliSenseLocalizer/releases 可以直接通过 `islocalizer install auto` 子命令进行安装（从github下载，可能比较慢，有梯子比较好）

使用 `islocalizer 子命令 -h` 可以查看大多数功能的帮助信息。
