### ISSUE TITLE
请问3种包有什么区别

### ISSUE THREAD

**Issue by mq00fc** [stratosblue/IntelliSenseLocalizer#3]
请问
net7.0@zh-cn@LocaleFirst.zip
net7.0@zh-cn@None.zip
net7.0@zh-cn@OriginFirst.zip
有什么区别吗？

**Comment by stratosblue** [comment]
@mq00fc 
由于官网翻译质量参差不齐，所以可选的提供了保留了原始文档的功能，以便能正确理解注释

LocaleFirst: 本地化文档在前
None: 没有保留原始文档
OriginFirst: 原始文档在前

**Comment by mq00fc** [comment]
@stratosblue 
非常感谢您，这对英语不好的人帮助极大！
