### ISSUE TITLE
Can't install .net7.0 version

### ISSUE THREAD

**Issue by luojianxhlxt** [stratosblue/IntelliSenseLocalizer#9]
after i use the code 

`islocalizer install auto -m net7.0 -l zh-cn -cc LocaleFirst`

to try to install the .net7 IntelliSenseLocalizer, this tool will install .net8 version by default
![微信截图_20240105131355](https://github.com/stratosblue/IntelliSenseLocalizer/assets/8614534/c7e7cc73-bef3-4047-aaa5-d2a7b9bf3897)

**Comment by stratosblue** [comment]
There has a small error here. Now fixed in version 1.1.2. Please use command 'dotnet tool update -g islocalizer' to update and try it again.
